plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'
	//id 'io.freefair.lombok' version '6.3'
}

group = 'com.tblmonitoring'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-parameters']
    options.release = 17
}



configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {


	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.security:spring-security-crypto'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'com.opencsv:opencsv:5.7.1'  // or latest version
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	implementation 'org.apache.poi:poi:5.2.5'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'
    
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'org.apache.xmlbeans:xmlbeans:5.1.1'
    implementation 'org.apache.commons:commons-compress:1.21'
    
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	
	  // Runtime dependencies for signature and parsing
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5' // for JSON parsing
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	implementation 'com.google.zxing:core:3.5.0'
    implementation 'com.google.zxing:javase:3.5.0'
    
     implementation 'org.springframework.boot:spring-boot-starter-mail'
     
     implementation 'jakarta.mail:jakarta.mail-api:2.1.1'
     
     implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
     
     
implementation 'com.sun.mail:jakarta.mail:2.0.1'
     implementation 'jakarta.mail:jakarta.mail-api:2.1.2'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-parameters'
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ["-parameters"]
}



tasks.withType(JavaCompile) {
    options.compilerArgs += ['-parameters']
}

