spring.application.name=TBL Monitor

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/machinemonitoringdb
spring.datasource.username=cdi_user
spring.datasource.password=CDITBL@1234

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Jackson Date/Time Serialization fix
spring.jackson.serialization.write-dates-as-timestamps=false


# Thymeleaf (if used)
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


spring.web.resources.static-locations=file:uploads/


# JWT Configuration
jwt.secret=kb/4d/HzWNeGa3pVK/E4gbOP4dm2x0Qc3rGzL5JLsENA/YYid10cg1xEhH8O8px5wiI1GDg2hY0eNbVawihgIQ==
jwt.expiration=86400000

app.upload-dir=uploads/qc-reports


spring.mail.username=chaitanyatandale05@gmail.com
spring.mail.password=mvhf ixlo imlz wfth
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# allow binding to any network interface (for local testing)
server.address=0.0.0.0

